cmd:
  type: python-venv
  command:
    default: python -u run.py
  path:
    default: ~/.opereto/operetovenv
item_properties:
-   direction: input
    editor: text
    key: bucket_name
    mandatory: true
    type: text
    value:
-   direction: input
    editor: text
    key: source_path
    mandatory: true
    type: text
    value:
    help: s3 source path of file or directory
-   direction: input
    editor: text
    key: target_path
    mandatory: true
    type: text
    value:
    help: local path of file or directory
-   editor: checkbox
    key: is_directory
    direction: input
    mandatory: false
    type: boolean
    value: false
    help: If checked, the service code will fetch the s3 content recoursively as a directory
-   editor: text
    key: aws_access_key
    direction: input
    mandatory: true
    store: []
    type: text
    help: AWS access key
    value: GLOBALS.opereto-aws-services-aws_access_key
-   editor: text
    key: aws_secret_key
    mandatory: true
    direction: input
    store: []
    type: text
    help: AWS secret key
    value: GLOBALS.opereto-aws-services-aws_secret_key

timeout: 1800
type: action
